kind: ConfigMap
apiVersion: v1
metadata:
  name: {{ template "eric-data-document-database-pg.fullname" . }}-metrics
  labels:
    app: {{ template "eric-data-document-database-pg.name" . }}
    chart: {{ template "eric-data-document-database-pg.chart" . }}
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
data:
  queries.yaml: |-
{{ toYaml .Values.metrics.queryMetrics | indent 4 }}