apiVersion: v1
kind: Secret
metadata:
  name: {{ template "eric-data-document-database-pg.fullname" . }}
  labels:
    app: {{ template "eric-data-document-database-pg.name" . }}
    chart: {{ template "eric-data-document-database-pg.chart" . }}
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
type: Opaque
data:
  {{ if .Values.postgresPassword }}
  postgres-password:  {{ .Values.postgresPassword | b64enc | quote }}
  {{ else }}
  postgres-password: {{ randAlphaNum 10 | b64enc | quote }}
  {{ end }}
  {{- if .Values.metricsDefPwd }}
  metrics-default-pwd: {{ .Values.metricsDefPwd | b64enc | quote }}
  {{- end }}
  {{ if .Values.postgresDefPwd }}
  postgres-default-pwd: {{ .Values.postgresDefPwd | b64enc | quote }}
  {{ else }}
  postgres-default-pwd: {{ randAlphaNum 10 | b64enc | quote }}
  {{ end }}
  {{- if .Values.persistence.backup.replicaPwd }}
  replica-default-pwd: {{ .Values.persistence.backup.replicaPwd | b64enc | quote }}
  {{- end }}
