apiVersion: v1
kind: Service
metadata:
  name: {{ template "eric-data-document-database-pg.fullname" . }}
  labels:
    app: {{ template "eric-data-document-database-pg.name" . }}
    chart: {{ template "eric-data-document-database-pg.chart" . }}
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
{{- if .Values.metrics.enabled }}
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: {{ .Values.metrics.service.port | quote }}
{{- end }}
spec:
  type: {{ .Values.service.type }}
  ports:
  - name: postgresql
    port: {{ .Values.service.port }}
    targetPort: postgresql
  {{- if (and (eq .Values.service.type "NodePort") (not (empty .Values.service.nodePort))) }}
    nodePort: {{ .Values.service.nodePort }}
  {{- end }}
  - name: metrics
    port: {{ .Values.metrics.service.port }}
    targetPort: metrics
  {{- if (and (eq .Values.service.type "NodePort") (not (empty .Values.metrics.service.nodePort))) }}
    nodePort: {{ .Values.metrics.service.nodePort }}
  {{- end }}
{{- if .Values.service.externalIPs }}
  externalIPs:
{{ toYaml .Values.service.externalIPs | indent 4 }}
{{- end }}
  selector:
    app: {{ template "eric-data-document-database-pg.name" . }}
